### ISSUE TITLE
Layer operation buttons not working

### ISSUE THREAD

**Issue by qingyezeng** [cmv/cmv-wab-widgets#28]
When trying CMV WAB demo, in Layer list and click ellipsis button on the right of layer title, it keeps loading, but nothing shows up. 
![image](https://user-images.githubusercontent.com/502763/42058342-22a7183e-7aee-11e8-8ccb-d6178ce94e46.png)

 In browser debug window, got the errors:

```
init.js:114 TypeError: window.getAppConfig is not a function
    at Object._getBasicItemInfo (LayerInfo.js:1106)
    at Object.isItemLayer (LayerInfo.js:992)
    at Object._getATagLabel (PopupMenuInfo.js:51)
    at Object._initCandidateMenuItems (PopupMenuInfo.js:117)
    at Object.constructor (PopupMenuInfo.js:43)
    at new <anonymous> (init.js:200)
    at Function.<anonymous> (PopupMenuInfo.js:471)
    at init.js:63
    at h (init.js:107)
    at d.then.b.then (init.js:110) "TypeError: window.getAppConfig is not a function
    at Object._getBasicItemInfo (https://cmv.github.io/cmv-wab-widgets/wab/2.8/jimu.js/LayerInfos/LayerInfo.js:1106:50)
    at Object.isItemLayer (https://cmv.github.io/cmv-wab-widgets/wab/2.8/jimu.js/LayerInfos/LayerInfo.js:992:19)
    at Object._getATagLabel (https://cmv.github.io/cmv-wab-widgets/wab/2.8/widgets/LayerList/PopupMenuInfo.js:51:43)
    at Object._initCandidateMenuItems (https://cmv.github.io/cmv-wab-widgets/wab/2.8/widgets/LayerList/PopupMenuInfo.js:117:21)
    at Object.constructor (https://cmv.github.io/cmv-wab-widgets/wab/2.8/widgets/LayerList/PopupMenuInfo.js:43:12)
    at new <anonymous> (https://js.arcgis.com/3.24/init.js:200:335)
    at Function.<anonymous> (https://cmv.github.io/cmv-wab-widgets/wab/2.8/widgets/LayerList/PopupMenuInfo.js:471:22)
    at https://js.arcgis.com/3.24/init.js:63:337
    at h (https://js.arcgis.com/3.24/init.js:107:277)
    at d.then.b.then (https://js.arcgis.com/3.24/init.js:110:152)
    ----------------------------------------
    rejected at a (https://js.arcgis.com/3.24/init.js:108:174)
    at h (https://js.arcgis.com/3.24/init.js:107:436)
    at d.then.b.then (https://js.arcgis.com/3.24/init.js:110:152)
    at Function.clazz.create (https://cmv.github.io/cmv-wab-widgets/wab/2.8/widgets/LayerList/PopupMenuInfo.js:450:30)
    at Object.openDropMenu (https://cmv.github.io/cmv-wab-widgets/wab/2.8/widgets/LayerList/PopupMenu.js:201:23)
    at Object._onPopupMenuClick (https://cmv.github.io/cmv-wab-widgets/wab/2.8/widgets/LayerList/LayerListView.js:549:21)
    at HTMLDivElement.<anonymous> (https://js.arcgis.com/3.24/init.js:63:15)
    ----------------------------------------
Error
    at d.then.b.then (https://js.arcgis.com/3.24/init.js:110:97)
    at Function.clazz.create (https://cmv.github.io/cmv-wab-widgets/wab/2.8/widgets/LayerList/PopupMenuInfo.js:450:30)
    at Object.openDropMenu (https://cmv.github.io/cmv-wab-widgets/wab/2.8/widgets/LayerList/PopupMenu.js:201:23)
    at Object._onPopupMenuClick (https://cmv.github.io/cmv-wab-widgets/wab/2.8/widgets/LayerList/LayerListView.js:549:21)
    at HTMLDivElement.<anonymous> (https://js.arcgis.com/3.24/init.js:63:15)"
```

**Comment by tmcgee** [comment]
@qingyezeng Thanks for reporting this. WebAppBuilder pollutes the global namespace with many variables/functions like `window.getAppConfig` while also providing `ConfigManager` module to do the same  I'll look into it as time permits.
